"""Does the challenger beat the incumbent, after correcting for variants tried?

`FEATURES.md` §8, VX-010. The corpus also settles which test: *"White's Reality
Check explicitly superseded - Hansen's SPA strictly dominates it; running both is
ceremony."*

**Why SPA dominates RC**, since it is the only reason to prefer the harder test.
White's Reality Check builds its null distribution from *every* candidate. Add fifty
hopeless variants and the critical value rises, so a genuinely good challenger gets
buried by the company it kept - the search is punished for having looked, rather
than corrected for it. Hansen recenters: a candidate whose mean performance falls
far enough below the benchmark is held at zero in the null, so junk can no longer
shield the incumbent. Both p-values are returned so the difference is inspectable
rather than asserted.

The mechanics, on `d_k,t = challenger_k performance − incumbent performance`:

    T_SPA = max_k  max( √n · mean(d_k) / ω_k , 0 )

studentised by ω_k, the stationary-bootstrap standard error of `mean(d_k)`. The null
is generated by stationary-bootstrap resampling of the aligned `d` series, recentred
by

    μ_k = mean(d_k) · 1{ mean(d_k) ≥ −A_k },   A_k = ¼ · n^(−¼) · ω_k

which is Hansen's consistent recentring. Setting `A_k = ∞` recovers White's RC, and
that is precisely how `p_value_reality_check` is computed - one code path, so the two
cannot drift apart.

**The prior art was read and rejected as a donor.** `nse-crypto-bot-final/trading/
strategy/generators/stats_gate.py` wraps `arch.bootstrap.StepM`, and:

*Its benchmark is `pd.Series(np.zeros(T))`* - a do-nothing zero-return series. That
tests "did this beat cash", which nearly everything passes in a rising market, not
"does the challenger beat the incumbent", which is what a promotion decides.

*It fails open, by declared design:* `except Exception: return all_ids`, documented
as *"so it can only ever ADD strictness when statistically meaningful, never silently
block the whole portfolio."* Coherent as a layered filter, but the consequence is
that a missing install, a NaN, or a library upgrade makes every candidate pass
family-wise error control silently and permanently. `arch` was not present in this
project's environment before this module was written - the exact condition under
which that branch reports a full pass having tested nothing. It is the fourth defect
found in this corpus that fails in the flattering direction.

So this module raises where it cannot test. "We could not check" and "it passed" are
different facts, and only one of them should let capital move.

**No third-party statistics dependency.** `arch` is installed in this environment as
a *verification* tool: `tests/test_superior_predictive_ability.py` cross-checks this
implementation against `arch.bootstrap.SPA`, Hansen's reference, because a bootstrap
p-value has no closed form to check against. The runtime path here is stdlib only.
"""
from __future__ import annotations

import math
import random
from dataclasses import dataclass
from statistics import mean

# Below this the bootstrap is describing its own resampling rather than the data.
# The donor's threshold was 8 paths, which for a studentised max-statistic over
# several candidates is not enough to place a tail quantile.
_MIN_PATHS = 20

_DEFAULT_BLOCK = 50


class NotEnoughPaths(ValueError):
    """Too few aligned observations for the test to mean anything.

    Raised rather than returning a pass. This is the deliberate inversion of the
    donor's fail-open branch.
    """


@dataclass(frozen=True)
class SpaResult:
    """The verdict, both p-values, and what it corrected for."""

    p_value: float                 # Hansen's consistent SPA
    p_value_reality_check: float   # same machinery, no recentring: White's RC
    test_statistic: float
    superior: tuple[str, ...]
    n_challengers: int
    n_paths: int
    n_bootstrap: int
    detail: str


def _stationary_bootstrap_indices(n: int, mean_block: int,
                                  rng: random.Random) -> list[int]:
    """Politis-Romano index path: geometric block lengths, circular wrap.

    The same scheme as `risk.drawdown_distribution`, for the same reason - it
    preserves the serial dependence in the performance differences, which is what
    makes the bootstrap standard error honest for time-series data.
    """
    p_new = 1.0 / mean_block
    out: list[int] = []
    index = rng.randrange(n)
    for _ in range(n):
        out.append(index)
        index = rng.randrange(n) if rng.random() < p_new else (index + 1) % n
    return out


def superior_predictive_ability(
    incumbent: list[float],
    challengers: dict[str, list[float]],
    n_bootstrap: int = 1000,
    block_size: int = _DEFAULT_BLOCK,
    seed: int = 0,
    alpha: float = 0.05,
) -> SpaResult:
    """Hansen's SPA test of every challenger against the incumbent at once.

    `incumbent` and each challenger are aligned per-period performance series - the
    same periods, in the same order. Misalignment raises rather than being truncated:
    two candidates scored over different periods are not comparable, and trimming to
    the shorter hides that the comparison was never valid.
    """
    if not challengers:
        raise ValueError(
            "no challengers supplied; there is no promotion decision to make")

    n = len(incumbent)
    if n < _MIN_PATHS:
        raise NotEnoughPaths(
            f"need >= {_MIN_PATHS} aligned observations for SPA, got {n}. Refused "
            f"rather than passed: a gate that cannot test must not report a pass")
    for name, series in challengers.items():
        if len(series) != n:
            raise ValueError(
                f"challenger {name!r} has {len(series)} observations against the "
                f"incumbent's {n}. Refused rather than truncated - candidates "
                f"scored over different periods are not comparable, and trimming "
                f"would hide that")

    names = tuple(challengers)
    # d > 0 means the challenger outperformed the incumbent in that period.
    differences = {k: [c - b for c, b in zip(challengers[k], incumbent)]
                   for k in names}
    means = {k: mean(differences[k]) for k in names}

    rng = random.Random(seed)
    index_paths = [_stationary_bootstrap_indices(n, max(2, block_size), rng)
                   for _ in range(n_bootstrap)]

    # omega_k is the asymptotic standard deviation of **√n · mean(d_k)**, not of
    # mean(d_k). Since Var(mean) ≈ ω²/n, that means ω = √n · SD(bootstrap means).
    #
    # The √n is not cosmetic, and it was caught by the cross-check against
    # `arch.bootstrap.SPA` rather than by reasoning. The p-value is invariant to ω's
    # scale - it divides both the statistic and the null - but Hansen's recentring
    # threshold A_k = ¼·n^(−¼)·ω_k is compared directly against mean(d_k). With ω
    # a factor √n too small, the threshold is too tight, almost nothing gets
    # recentred to zero, and the "consistent" SPA quietly degenerates toward the
    # White's Reality Check it is supposed to dominate. On the cross-check data that
    # showed as p=0.0619 against the reference's 0.0240 - the same side of zero,
    # opposite sides of alpha=0.05.
    #
    # Studentising at all is what lets one max-statistic compare candidates with
    # different volatilities; without it the noisiest candidate wins the max on
    # scale alone.
    bootstrap_means = {
        k: [mean([differences[k][i] for i in path]) for path in index_paths]
        for k in names
    }
    omega = {}
    for k in names:
        centred = [bm - means[k] for bm in bootstrap_means[k]]
        standard_error = math.sqrt(sum(c * c for c in centred) / len(centred))
        omega[k] = math.sqrt(n) * standard_error
        if omega[k] <= 0.0:
            raise ValueError(
                f"challenger {k!r} has zero bootstrap variance in its performance "
                f"difference against the incumbent - the two series are effectively "
                f"identical, and a significant verdict there would promote a "
                f"challenger for being indistinguishable")

    root_n = math.sqrt(n)
    statistic = max(0.0, max(root_n * means[k] / omega[k] for k in names))

    def null_distribution(recentre: bool) -> list[float]:
        """Bootstrap the max-statistic under the null.

        `recentre=True` is Hansen's consistent SPA: candidates far enough below the
        benchmark are held at zero, so hopeless variants stop inflating the critical
        value. `recentre=False` keeps every candidate's mean and is White's Reality
        Check - the same code path, so the two can never drift apart.
        """
        if recentre:
            threshold = {k: 0.25 * (n ** -0.25) * omega[k] for k in names}
            centre = {k: (means[k] if means[k] >= -threshold[k] else 0.0)
                      for k in names}
        else:
            centre = dict(means)

        out = []
        for path_index, path in enumerate(index_paths):
            best = 0.0
            for k in names:
                resampled = bootstrap_means[k][path_index]
                best = max(best, root_n * (resampled - centre[k]) / omega[k])
            out.append(best)
        return out

    def p_value_from(null: list[float]) -> float:
        # (#{null >= statistic} + 1) / (B + 1): the +1 keeps the p-value strictly
        # positive, so a finite bootstrap never reports impossibility.
        exceed = sum(1 for value in null if value >= statistic)
        return (exceed + 1) / (len(null) + 1)

    p_consistent = p_value_from(null_distribution(recentre=True))
    p_reality_check = p_value_from(null_distribution(recentre=False))

    # Named superior only when the family-wise test rejects AND the candidate
    # individually beat the incumbent. Without the family-wise gate this is a
    # per-candidate comparison with no multiplicity correction at all.
    superior: tuple[str, ...] = ()
    if p_consistent < alpha:
        superior = tuple(k for k in names if means[k] > 0.0)

    return SpaResult(
        p_value=p_consistent,
        p_value_reality_check=p_reality_check,
        test_statistic=statistic,
        superior=superior,
        n_challengers=len(names),
        n_paths=n,
        n_bootstrap=n_bootstrap,
        detail=(f"SPA p={p_consistent:.4f} (RC p={p_reality_check:.4f}) over "
                f"{len(names)} challengers and {n} aligned paths, "
                f"{n_bootstrap} stationary-bootstrap reps at block {block_size}; "
                f"statistic {statistic:.4f}, alpha {alpha}"),
    )
